Finish rough draft of new lesson content
learn-co-curriculum/javascript-intro-to-variable-assignment-and-declaration pull request #14
Opened 2017-07-27 20:55 UTC by gj

2017-07-31 18:26 UTC, jmburges requested changes

2017-07-31 18:26 UTC, jmburges commented on README.md
> +Imagine a box that can hold any type of data: a number, string, boolean, object — even an `undefined`. We take some data that we want to store, place it inside the box, and hand the box off to the Ja
really like this definition of a variable. IT's so hard to explain

2017-07-31 18:26 UTC, jmburges commented on README.md
> +If you're interested in an exhaustive discussion of what constitutes a valid variable name in JavaScript, [have fun][valid variable names]. For almost every situation, follow these three rules, and y
Tell them not to look at that unless you're super bored. I want to focus the student's attention

2017-07-31 18:26 UTC, jmburges commented on README.md
> +The `var` reserved word is the classic way to declare a variable. It's been around since the inception of JavaScript, and it's what you will encounter in any pre-ES2015 code (and in any sloppy code w
Do they know what ES2015 is?

2017-07-31 18:26 UTC, jmburges commented on README.md
> +The `var` reserved word is the classic way to declare a variable. It's been around since the inception of JavaScript, and it's what you will encounter in any pre-ES2015 code (and in any sloppy code w
Dont mention the sloppy code thing. Mayn students will end up with code that uses var. I don't want them to get a bad taste in their mouth for it.

2017-07-31 18:26 UTC, jmburges commented on README.md
> +As we alluded to earlier, there is almost no reason to use `var` in a post-ES2015 world. `var` comes with a ton of baggage in the form of scope issues, which we will discuss in the lesson on scope in
So why did we show it to folks? StackOverflow

2017-07-31 18:26 UTC, jmburges commented on README.md
> +1. When we assign a primitive value (a number, string, boolean, etc. — anything except an object) to a variable declared with `const`, we know that variable will _always_ contain the same value.
They don't really know what primitives are

2017-07-31 18:38 UTC, gj commented on README.md
> +The `var` reserved word is the classic way to declare a variable. It's been around since the inception of JavaScript, and it's what you will encounter in any pre-ES2015 code (and in any sloppy code w
>Do they know what ES2015 is?

Yes, will be in Intro to JavaScript lesson

>Dont mention the sloppy code thing. Many students will end up with code that uses var. I don't want them to get a bad taste in their mouth for it.

You mean once they get out into the world they'll see `var`? Happy to remove

2017-07-31 18:40 UTC, gj commented on README.md
> +As we alluded to earlier, there is almost no reason to use `var` in a post-ES2015 world. `var` comes with a ton of baggage in the form of scope issues, which we will discuss in the lesson on scope in
because "it's what [they] will encounter in any pre-ES2015 code", but yeah should probably reiterate that it's pretty ubiquitous

2017-07-31 18:41 UTC, gj commented on README.md
> +1. When we assign a primitive value (a number, string, boolean, etc. — anything except an object) to a variable declared with `const`, we know that variable will _always_ contain the same value.
@jmburges 

I can probably remove "primitive" and just make the distinction "number, string, boolean, symbol, undefined, null" vs. "object"

2017-07-31 20:58 UTC, gj commented on README.md
> +1. When we assign a primitive value (a number, string, boolean, etc. — anything except an object) to a variable declared with `const`, we know that variable will _always_ contain the same value.
Added a note on primitives to previous lesson + clarified language here a bit.

2017-08-01 02:27 UTC, gj commented
Closing in favor of https://github.com/learn-co-curriculum/js-basics-variables-readme.

2017-08-01 02:27 UTC, closed without merging